### ISSUE TITLE
Crashes on ESP8266

### ISSUE THREAD

**Issue by BJvDL** [adafruit/Adafruit_HTU21DF_Library#4] opened 2015-06-26 20:37 UTC
The example looks OK after implementing issue #3  but in my first test it crashes after a few readings. 
I need to hard reset to get it working again.
I'm using the nightly build version 1.6.4-835-g77d77e8 from github.com/esp8266/arduino with the Arduino board installer

rHTU21D-F test
Temp: 24.97     Hum: 56.76
Temp: 41.01     Hum: 56.73
Temp: 24.97     Hum: 56.75
Temp: 24.98     Hum: 56.69
Temp: 24.97     Hum: 56.63
Temp: 24.97     Hum: 56.60
Temp: 24.95     Hum: 56.54
Temp: 24.98     Hum: 57.45
Temp: 25.00     Hum: 57.35
Temp: 24.98     Hum: 57.18
Temp: 24.98     Hum: 57.08
Temp: 24.99     Hum: 56.94
Temp: 24.98     Hum: 56.88
Temp: 
ctx: cont 
sp: 3ffe9b60 end: 3ffe9d40 offset: 01b0

> > > stack>>>
> > > 3ffe9d10:  40201c75 3ffe8bf0 3ffe9d98 40202158  
> > > 3ffe9d20:  00000000 00000000 3ffe9d64 40201cce  
> > > 3ffe9d30:  00000000 00000000 3ffe8d20 40100118  
> > > <<<stack<<<

 ets Jan  8 2013,rst cause:1, boot mode:(1,7)

 ets Jan  8 2013,rst cause:4, boot mode:(1,7)

wdt reset

**Comment by bbx10** [comment] 2015-06-26 21:50
ESP8266 HUZZAH + HTU21DF breakout boards have been running for 5 minutes without crashing. I increased the Serial speed to 115200 but that should not make any difference.
My setup is the ESP8266 board is powered by 4xAA alkaline batteries providing about 6V DC into the HUZZAH VBAT pin. The HTU21DF board is powered from the HUZZAH 3V pin. HUZZAH GPIO#4 pin connects to the HTU21DF SDA pin. HUZZAH GPIO#5 connects to HTU21DF SCL pin. Also HUZZAH RST is connected to HUZZAH GPIO#16. This allows deep sleep to work but it is currently not being used.

**Comment by microbuilder** [comment] 2018-10-01 17:09
Haven't been able to reproduce this ... I'm going to close the issue since it might have been resolved with recent changes, but feel free to reopen!

**Closed by microbuilder** 2018-10-01 17:09 UTC
